### ISSUE TITLE
CTD, Savegame Corruption On Placing Galacticraft Lightning Panel

### ISSUE THREAD

**Issue by midorlo** [asiekierka/FoamFix#132]
Placing a Galacticraft lightning panel under certain circumstance causes a client crash. Furthermore, the SSP savegame becomes permanently corrupted, reproducing the crash on client login. The stacktrace seems to be related to foamfix:

```
java.lang.IllegalArgumentException: Cannot get unlisted property appeng.block.UnlistedDirection@7c10b885 as it does not exist in ExtendedBlockState{block=galacticraftcore:panel_lighting, properties=[type]}
	at pl.asie.foamfix.common.FoamyExtendedBlockState.getValue(FoamyExtendedBlockState.java:136)
	at appeng.client.render.model.AutoRotatingModel.func_188616_a(AutoRotatingModel.java:155)
	at micdoodle8.mods.galacticraft.core.client.model.block.ModelPanelLightBase.func_188616_a(ModelPanelLightBase.java:45)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render_foamfix_old(ForgeBlockModelRenderer.java:99)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:44)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:64)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:47)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:64)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Unknown Source)
```

Full crash report is [here](https://pastebin.com/raw/Yjn2n31L).

Client Setup: [Modern Skyblock 3](https://minecraft.curseforge.com/projects/modern-skyblock-3-departed) v3.2.0.1(current stable), spawned via Curse Client, defaults, no optifine (Was in..  I removed it for debugging purposes and got the same crash on relog).

Runtime: JRE8_161b12 `-XX:+UseG1GC -Xmx6G -Xms6G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`

System: Generic win10x64 consumer desktop, stable channel updates, nothing interferencing, nothing of interest to add here.

Notes: Has to have to do with the individual position (Edge, Next to Exu polished stone, Tier3 Mekanism Compressor, AE2 cable and TE Item duct), because I cannot replicate it in a fresh save. Yet my current savegame is permanently damaged. Forge's option to remove erroring entities/tile-entitites did not work (happily taking ideas, rollback would lose me a day).

**Comment by asiekierka** [comment]
This doesn't happen without FoamFix, does it? Did you check? This code in FoamFix emulates vanilla/Forge behaviour very closely and is misblamed surprisingly often - only once (with BiblioCraft) out of dozens of reports has it actually been unreproducible without FoamFix.

>happily taking ideas

This is most likely a Galacticraft bug. I recommend removing the affected block with MCEdit!

**Comment by midorlo** [comment]
I tried to test without Foamfix, tbh the 6GB RAM I can affort to allocate wont even run the pack to main menu :-( 

Meanwhle I succesfully deleted the block using MCEdit and can resume the savegame. I'll reference this to galacticrafts issue system. Sorry for the trouble.

**Comment by asiekierka** [comment]
Try to reproduce without FoamFix first anyway, as they'll probably tell you to do the same. Perhaps on a smaller pack? GC and AE2 interactions are implicated, most likely with some sort of camouflage - you might be able to get away with just the two mods.

**Comment by midorlo** [comment]
I'll see what I can do, copy the instance and delete content until it's able to load up on 6g.
