### ISSUE TITLE
NoSuchMethodError with latest 1.12.2 Foamfix Anarchy 0.9.7

### ISSUE THREAD

**Issue by darthvader45** [asiekierka/FoamFix#138]
Been getting this crash regularly, not sure why though.  It seems to mention a broken method call in FoamyItemLayerModel.  

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.6-1.12.2-anarchy.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  LoadingPlugin (Quark-r1.4-121.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-76-core.jar)
  FarseekCoreMod (Farseek-1.12-2.2.3.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.11.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 4/11/18 3:38 PM
Description: Initializing game

com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: net.minecraftforge.common.model.TRSRTransformation.isIdentity()Z
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bake(ModelLoader.java:444)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:193)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.common.model.TRSRTransformation.isIdentity()Z
	at pl.asie.foamfix.client.FoamyItemLayerModel.bakeStatic(FoamyItemLayerModel.java:335)
	at net.minecraftforge.client.model.ItemLayerModel.bake(ItemLayerModel.java:80)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bakeImpl(ModelLoader.java:471)
	at net.minecraftforge.client.model.ModelLoader$VanillaLoader$1.load(ModelLoader.java:841)
	at net.minecraftforge.client.model.ModelLoader$VanillaLoader$1.load(ModelLoader.java:837)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 25 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bake(ModelLoader.java:444)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:193)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2256362448 bytes (2151 MB) / 4501012480 bytes (4292 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8192m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 Optifine OptiFine_1.12.2_HD_U_D1 53 mods loaded, 53 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version         | Source                                        | Signature                                |
	|:----- |:-------------------- |:--------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft            | 1.12.2          | minecraft.jar                                 | None                                     |
	| UCH   | mcp                  | 9.42            | minecraft.jar                                 | None                                     |
	| UCH   | FML                  | 8.0.99.99       | forge-1.12.2-14.23.2.2611-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                | 14.23.2.2611    | forge-1.12.2-14.23.2.2611-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | foamfixcore          | 7.7.4           | minecraft.jar                                 | None                                     |
	| UCH   | securitycraft        | v1.8.4.1        | [1.12.x]+SecurityCraft+v1.8.4.1.jar           | None                                     |
	| UCH   | craftstudioapi       | 1.0.0           | CraftStudio-1.0.0.93-mc1.12-alpha.jar         | None                                     |
	| UCH   | quark                | r1.4-121        | Quark-r1.4-121.jar                            | None                                     |
	| UCH   | animania             | 1.4.7           | animania-1.12.2-1.4.7.jar                     | None                                     |
	| UCH   | autoreglib           | 1.3-15          | AutoRegLib-1.3-15.jar                         | None                                     |
	| UCH   | betterfoliage        | 2.1.10          | BetterFoliage-MC1.12-2.1.10.jar               | None                                     |
	| UCH   | bibliocraft          | 2.4.3           | BiblioCraft[v2.4.3][MC1.12.0].jar             | None                                     |
	| UCH   | codechickenlib       | 3.1.6.339       | CodeChickenLib-1.12.2-3.1.6.339-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | cookingforblockheads | 6.3.17          | CookingForBlockheads_1.12.1-6.3.17.jar        | None                                     |
	| UCH   | extendedrenderer     | v1.0            | coroutil-1.12.2-1.1.22.jar                    | None                                     |
	| UCH   | coroutil             | 1.12.1-1.1.20   | coroutil-1.12.2-1.1.22.jar                    | None                                     |
	| UCH   | configmod            | v1.0            | coroutil-1.12.2-1.1.22.jar                    | None                                     |
	| UCH   | cyberware            | 0.2.10.9        | cyberware-1.12.2-0.2.10.9.jar                 | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| UCH   | ptrmodellib          | 1.0.2           | PTRLib-1.0.2.jar                              | None                                     |
	| UCH   | props                | 2.6.0           | Decocraft-2.6.0_1.12.2.jar                    | None                                     |
	| UCH   | cdm                  | 0.3.1           | device-mod-0.3.1-1.12.2.jar                   | None                                     |
	| UCH   | dsurround            | 3.4.9.11        | DynamicSurroundings-1.12.2-3.4.9.11.jar       | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCH   | presets              | 3.4.9.11        | DynamicSurroundings-1.12.2-3.4.9.11.jar       | None                                     |
	| UCH   | earthworks           | 1.3.4.3         | Earthworks-1.12-1.3.6.jar                     | None                                     |
	| UCH   | exnihilocreatio      | 1.12-0.1.5      | exnihilocreatio-1.12-0.1.5.jar                | None                                     |
	| UCH   | excompressum         | 3.0.17          | ExCompressum_1.12.2-3.0.17.jar                | None                                     |
	| UCH   | farseek              | 2.2.3           | Farseek-1.12-2.2.3.jar                        | None                                     |
	| UCH   | flansmod             | 5.5.2           | Flan's Mod-1.12.2-5.5.2.jar                   | None                                     |
	| UCH   | flansmodapocalypse   | 1.0             | Flan's Mod-1.12.2-5.5.2.jar                   | None                                     |
	| UCH   | fluidfunnel          | 1.1.0           | FluidFunnel-1.12.2-1.1.0.jar                  | None                                     |
	| UCH   | foamfix              | 0.9.6-1.12.2    | foamfix-0.9.6-1.12.2-anarchy.jar              | None                                     |
	| UCH   | cfm                  | 4.1.5           | furniture-4.1.5-1.12.2.jar                    | None                                     |
	| UCH   | jei                  | 4.8.5.138       | jei_1.12.2-4.8.5.138.jar                      | None                                     |
	| UCH   | immersiveengineering | 0.12-76         | ImmersiveEngineering-0.12-76.jar              | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCH   | geolosys             | 1.8.8c          | Geolosys-1.12.2-1.8.8c.jar                    | None                                     |
	| UCH   | hopperducts          | 1.5             | hopperducts-mc1.12-1.5.jar                    | None                                     |
	| UCH   | icbmclassic          | 1.12.2-3.0.0.22 | ICBM-classic-1.12.2-3.0.0b22.jar              | None                                     |
	| UCH   | immersivepetroleum   | @VERSION@       | immersivepetroleum-1.12.2-1.1.6.jar           | None                                     |
	| UCH   | immersivetech        | 1.3.4           | immersivetech-1.12-1.3.4.jar                  | None                                     |
	| UCH   | incontrol            | 3.7.1           | incontrol-1.12-3.7.1.jar                      | None                                     |
	| UCH   | lunatriuscore        | 1.2.0.42        | LunatriusCore-1.12.2-1.2.0.42-universal.jar   | None                                     |
	| UCH   | ingameinfoxml        | 2.8.2.94        | InGameInfoXML-1.12.2-2.8.2.94-universal.jar   | None                                     |
	| UCH   | lightswitch          | 1.1.1           | lightswitch-1.1.1-mc1.12.2.jar                | None                                     |
	| UCH   | malisiscore          | 1.12.2-6.4.0    | malisiscore-1.12.2-6.4.0.jar                  | None                                     |
	| UCH   | malisisdoors         | 1.12.2-7.3.0    | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
	| UCH   | nei                  | 2.4.1           | NotEnoughItems-1.12.2-2.4.1.233-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | harvestcraft         | 1.12.2t         | Pam's+HarvestCraft+1.12.2t.jar                | None                                     |
	| UCH   | placeableitems       | 3.3             | placeableitems-3.3.jar                        | None                                     |
	| UCH   | sdrones              | 1.0             | sdrones-1.0.1.jar                             | None                                     |
	| UCH   | streams              | 0.4.2           | Streams-1.12-0.4.2.jar                        | None                                     |
	| UCH   | bspkrscore           | at_0.9          | Treecapitator-1.12-at_0.9a.jar                | None                                     |
	| UCH   | treecapitator        | at_0.9          | Treecapitator-1.12-at_0.9a.jar                | None                                     |
	| UCH   | zombieawareness      | 1.12.1-1.11.11  | zombieawareness-1.12.1-1.11.11.jar            | None                                     |

	Loaded coremods (and transformers): 
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.6-1.12.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
LoadingPlugin (Quark-r1.4-121.jar)
  vazkii.quark.base.asm.ClassTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-76-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
FarseekCoreMod (Farseek-1.12-2.2.3.jar)
  farseek.core.FarseekClassTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.11.jar)
  org.blockartistry.DynSurround.asm.Transformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GT 750M/PCIe/SSE2'
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: GeForce GT 750M/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_D1
	OptiFine Build: 20180323-135452
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 391.35
	OpenGlRenderer: GeForce GT 750M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
```

**Comment by asiekierka** [comment]
Update Forge or downgrade FoamFix ... 2654 is recommended at this point, but I still urge you to use latest.

**Comment by darthvader45** [comment]
Huh, I'll try that, can't guarantee it's compatible with my other loaded mods.  Glad to see you're still modding.
