### ISSUE TITLE
12.2 Version-0.9.7  Client crash 

### ISSUE THREAD

**Issue by AdaraChristine** [asiekierka/FoamFix#140]
foamfix-0.9.7-1.12.2-anarchy
Forge 14.23.2.2611

4/16/18 1:59 PM
Description: Initializing game

com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: net.minecraftforge.common.model.TRSRTransformation.isIdentity()Z
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bake(ModelLoader.java:444)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:193)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.common.model.TRSRTransformation.isIdentity()Z
	at pl.asie.foamfix.client.FoamyItemLayerModel.bakeStatic(FoamyItemLayerModel.java:335)
	at net.minecraftforge.client.model.ItemLayerModel.bake(ItemLayerModel.java:80)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bakeImpl(ModelLoader.java:471)
	at net.minecraftforge.client.model.ModelLoader$VanillaLoader$1.load(ModelLoader.java:841)
	at net.minecraftforge.client.model.ModelLoader$VanillaLoader$1.load(ModelLoader.java:837)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)

https://pastebin.com/Svyk1qbX

**Comment by asiekierka** [comment]
Update Forge or downgrade FoamFix to 0.9.5.
