### ISSUE TITLE
Error every time I try to open Vanilla chest.

### ISSUE THREAD

**Issue by mindcloud69** [asiekierka/FoamFix#149]
FoamFix 0.9.9.1 anarchy
forge 14.23..4.2707
ATM 3 modpack with ProjectRed and Immersive Railroads added

Every time I try top open a vanilla chest I can not and this appears in the console.  Mod chests work correctly.

Edit: The game does not crash 
here is a link to my [fomfix config.](https://gist.github.com/mindcloud69/fabd61cc684042ab72c5b2ce0663d772)

```
[23:30:57] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: pl.asie.foamfix.common.FoamyBlockState.doesSideBlockChestOpening(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.AbstractMethodError: pl.asie.foamfix.common.FoamyBlockState.doesSideBlockChestOpening(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z
	at net.minecraft.block.BlockChest.func_176456_n(BlockChest.java:541) ~[api.class:?]
	at net.minecraft.block.BlockChest.func_176457_m(BlockChest.java:536) ~[api.class:?]
	at net.minecraft.block.BlockChest.func_189418_a(BlockChest.java:460) ~[api.class:?]
	at net.minecraft.block.BlockChest.func_180676_d(BlockChest.java:444) ~[api.class:?]
	at net.minecraft.block.BlockChest.func_180639_a(BlockChest.java:421) ~[api.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:446) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```

**Comment by asiekierka** [comment]
>ProjectRed and Immersive Railroads added

Are you sure you don't have an outdated version of OptiFine?

**Comment by mindcloud69** [comment]
This is exactly what it was Thank you!

**Comment by asiekierka** [comment]
Next time, please be a bit more honest about which mods you added. Would make it easier. Thank you!
