### ISSUE TITLE
Server crash crash report

### ISSUE THREAD

**Issue by Beelzaboss** [asiekierka/FoamFix#169]
This crash only happens when foamfix is installed on the server.

`[16:38:31] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/world/chunk/BlockStateContainer
        at net.minecraft.world.chunk.storage.ExtendedBlockStorage.<init>(ExtendedBlockStorage.java:21) ~[axx.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(AnvilChunkLoader.java:447) ~[aye.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.checkedReadChunkFromNBT__Async(AnvilChunkLoader.java:128) ~[aye.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:92) ~[aye.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.run(ChunkIOProvider.java:70) ~[ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:92) ~[ChunkIOExecutor.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) ~[on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89) ~[on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.redirect$onProvideChunkHead$zmg000(ChunkProviderServer.java:674) ~[on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135) ~[on.class:?]
        at net.minecraft.server.MinecraftServer.prepareSpawnArea(MinecraftServer.java:3589) ~[MinecraftServer.class:?]
        at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:821) ~[WorldManager.class:1.12.2-2705-8.0.0-BETA-3402]
        at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:763) ~[WorldManager.class:1.12.2-2705-8.0.0-BETA-3402]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3541) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.chunk.BlockStateContainer
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
        ... 17 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521) ~[spongeforge-1.12.2-2705-8.0.0-BETA-3402.jar:1.12.2-2705-8.0.0-BETA-3402]
        at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[spongeforge-1.12.2-2705-8.0.0-BETA-3402.jar:1.12.2-2705-8.0.0-BETA-3402]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
        ... 17 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirect$onGetStorageSize$FixVanillaBug$zmd000(Lnet/minecraft/util/BitArray;)I in mixins.common.core.json:world.chunk.MixinBlockStateContainer failed injection check, (0/1) succeeded. Using refmap mixins.common.refmap.json
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:290) ~[spongeforge-1.12.2-2705-8.0.0-BETA-3402.jar:1.12.2-2705-8.0.0-BETA-3402]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1203) ~[spongeforge-1.12.2-2705-8.0.0-BETA-3402.jar:1.12.2-2705-8.0.0-BETA-3402]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:938) ~[spongeforge-1.12.2-2705-8.0.0-BETA-3402.jar:1.12.2-2705-8.0.0-BETA-3402]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:322) ~[spongeforge-1.12.2-2705-8.0.0-BETA-3402.jar:1.12.2-2705-8.0.0-BETA-3402]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280) ~[spongeforge-1.12.2-2705-8.0.0-BETA-3402.jar:1.12.2-2705-8.0.0-BETA-3402]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[spongeforge-1.12.2-2705-8.0.0-BETA-3402.jar:1.12.2-2705-8.0.0-BETA-3402]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) ~[spongeforge-1.12.2-2705-8.0.0-BETA-3402.jar:1.12.2-2705-8.0.0-BETA-3402]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) ~[spongeforge-1.12.2-2705-8.0.0-BETA-3402.jar:1.12.2-2705-8.0.0-BETA-3402]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) ~[spongeforge-1.12.2-2705-8.0.0-BETA-3402.jar:1.12.2-2705-8.0.0-BETA-3402]
        at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[spongeforge-1.12.2-2705-8.0.0-BETA-3402.jar:1.12.2-2705-8.0.0-BETA-3402]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
        ... 17 more
[16:38:31] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /root/ModdedLite/./crash-reports/crash-2018-08-25_16.38.31-server.txt
`

**Comment by asiekierka** [comment]
Remember when the FoamFix page said Sponge is unsupported? That's one of the reasons why.

[Duplicate + Workaround](https://github.com/asiekierka/FoamFix/issues/166)

**Comment by DrTHC** [comment]
really wish you would stop fucking closing things before they are sorted... this website has to be the WORST for information!!!!

**Comment by asiekierka** [comment]
But it is sorted. It's a duplicate of an existing issue - I made a link to the earlier issue, which also lists a workaround for the problem described in this (and earlier) issue. The linked issue remains open as of today.

And remember: If you don't like the mod, you don't have to use it.
