### ISSUE TITLE
Crash while loading chunks

### ISSUE THREAD

**Issue by BugmanBugman** [asiekierka/FoamFix#179]
---- Minecraft Crash Report ----
// I blame asiekierka, author of FoamFix.

Time: 2018-10-29 00:13:22 CDT
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot set property PropertyInteger{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3]} to 6 on block minecraft:beetroots, it is not an allowed value
    at pl.asie.foamfix.common.FoamyBlockState.withProperty(FoamyBlockState.java:59)
    at net.minecraft.block.BlockCrops.withAge(BlockCrops.java:61)
    at net.minecraft.block.BlockCrops.getStateFromMeta(BlockCrops.java:251)
    at net.theexceptionist.coherentvillages.worldgen.villages.FrankStructurePieces$Field2.addComponentParts(FrankStructurePieces.java:577)
    at net.minecraft.world.gen.structure.StructureStart.generateStructure(StructureStart.java:47)
    at net.minecraft.world.gen.structure.MapGenStructure.generateStructure(MapGenStructure.java:94)
    at net.minecraft.world.gen.ChunkGeneratorOverworld.populate(ChunkGeneratorOverworld.java:406)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1019)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:999)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:110)
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:89)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:135)
    at net.minecraft.world.World.getChunkFromChunkCoords(World.java:310)
    at net.minecraft.world.ChunkCache.<init>(ChunkCache.java:37)
    at net.minecraft.pathfinding.PathNavigate.getPathToPos(SourceFile:113)
    at net.minecraft.pathfinding.PathNavigateGround.getPathToPos(SourceFile:51)
    at net.minecraft.pathfinding.PathNavigateGround.getPathToEntityLiving(SourceFile:73)
    at net.minecraft.pathfinding.PathNavigate.tryMoveToEntityLiving(SourceFile:147)
    at net.minecraft.entity.ai.EntityAIFollowParent.updateTask(SourceFile:81)
    at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:129)
    at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:888)
    at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2352)
    at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:678)
    at net.minecraft.entity.EntityAgeable.onLivingUpdate(EntityAgeable.java:178)
    at net.minecraft.entity.passive.EntityAnimal.onLivingUpdate(SourceFile:43)
    at lykrast.defiledlands.common.entity.passive.EntityBookWyrm.onLivingUpdate(EntityBookWyrm.java:131)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2172)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:377)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1955)
    at net.minecraft.world.World.redirect$updateEntity$zbl000(World.java:4117)
    at net.minecraft.world.World.updateEntities(World.java:1759)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: defiledlands:book_wyrm (lykrast.defiledlands.common.entity.passive.EntityBookWyrm)
  Entity ID: 75550
  Entity Name: Book Wyrm
  Entity's Exact location: 391.50, 63.00, -87.50
  Entity's Block location: World: (391,63,-88), Chunk: (at 7,3,8 in 24,-6; contains blocks 384,0,-96 to 399,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
  Entity's Momentum: 0.00, -0.08, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {HurtByTimestamp:0,ForgeData:{},Digested:0,Attributes:[{Base:1.0d,Name:"lucraftcore.stepHeight"},{Base:0.0d,Name:"lucraftcore.extraPunchDamage"},{Base:0.0d,Name:"lucraftcore.fallResistance"},{Base:0.0d,Name:"lucraftcore.jumpHeight"},{Base:0.0d,Name:"lucraftcore.sprintSpeed"},{Base:12.0d,Name:"generic.maxHealth"},{Base:0.0d,Name:"generic.knockbackResistance"},{Base:0.26d,Name:"generic.movementSpeed"},{Base:0.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:1.0d,Name:"forge.swimSpeed"},{Base:64.0d,Modifiers:[{UUIDMost:7613919428513580819L,UUIDLeast:-8190941215611620369L,Amount:0.038941859798306055d,Operation:1,Name:"Random spawn bonus"}],Name:"generic.followRange"}],Invulnerable:0b,FallFlying:0b,ForcedAge:0,PortalCooldown:0,AbsorptionAmount:0.0f,MaxLvl:6,FallDistance:0.0f,InLove:0,DeathTime:0s,ForgeCaps:{"avp:organism":{BPM:63},"epicsiegemod:modified_handler":{data:{},modified:0b},"thebetweenlands:custom_step_sound":{},"llibrary:extendedentitydatacapability":{"mm:living":{frozenYaw:0.0f,freezeProgress:0.0f,frozenPitch:0.0f,frozenYawHead:0.0f,frozenEntityID:-1,frozenLimbSwingAmount:0.0f,frozenRenderYawOffset:0.0f,frozenSwingProgress:0.0f},"Ice And Fire - Chicken Property Tracker":{TimeUntilNextEgg:0},"Ice And Fire - Siren Property Tracker":{CharmedBySiren:0b},"Ice And Fire - Frozen Property Tracker":{TicksUntilUnfrozen:0,IsFrozen:0b},"Ice And Fire - Stone Property Tracker":{StoneBreakLvl:0,TurnedToStone:0b}},"lucraftcore:size_changing":{EstimatedSize:0.0f,OrigWidth:0.45f,Size:1.0f,OrigHeight:0.45f,SizePerTick:0.0f,SizeChanger:"lucraftcore:default"},"thebetweenlands:puppet":{ticks:0},"twilightforest:cap_shield":{permshields:0,tempshields:0},"grimpack:ifrozencapability":{IsFrozen:0b,Duration:0,Time:0},"scp:eternalflame":{OnFire:0b},"lycanitesmobs:iextendedentity":{},"scp:zombie_plague":{Duration:0,Infected:0b},"thebetweenlands:entity_gems":{gems:[]},"techguns:deathtype":{},"voidcraft:voidicinfusioncapabilityhandler":{infusion:0,maxInfusion:6000,xiaDefeats:0.0f},"scp:shadowinfestation":{InfestationLevel:0,InfestationTime:-1},"thebetweenlands:equipment":{amuletSlots:1},"scp:crystallization":{Duration:0,Crystallized:0b},"cavern:portal_cache":{LastPos:[],LastDim:[]},"scp:render":{ShouldRender:0b},"reforged:reforgedplayer":0b},HandDropChances:[0.085f,0.085f],PersistenceRequired:0b,Age:-23990,Golden:0b,Motion:[0.0d,-0.0784000015258789d,0.0d],Leashed:0b,UUIDLeast:-8793767530138132928L,Health:12.0f,Digest:201,LeftHanded:0b,Air:300s,OnGround:1b,Dimension:0,Rotation:[105.42013f,0.0f],UpdateBlocked:0b,HandItems:[{},{}],DigestTimer:0,ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],Digesting:0,UUIDMost:-1045716539937568967L,Pos:[391.5d,63.0d,-87.5d],Fire:-1s,ArmorItems:[{},{},{},{}],CanPickUpLoot:0b,HurtTime:0s}

-- Affected level --
  Level name: Titan
  All players: 1 total; [GCEntityPlayerMP['Velocihater'/439, l='Titan', x=313.60, y=69.71, z=-39.92]]
  Chunk stats: ServerChunkCache: 837 Drop: 0
  Level seed: 3597958547531978806
  Level generator: ID 07 - jungle, ver 0. Features enabled: true
  Level generator options: 
  Level spawn location: World: (200,64,256), Chunk: (at 8,4,0 in 12,16; contains blocks 192,0,256 to 207,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 1284045 game time, 1414591 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 156624 (now: false), thunder time: 103384 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_181, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1598065560 bytes (1524 MB) / 7784759296 bytes (7424 MB) up to 11166941184 bytes (10649 MB)
  JVM Flags: 10 total; -Xmx12288m -Xms256m -XX:PermSize=256m -Xmx11G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:+UseParNewGC -XX:-UseAdaptiveSizePolicy -Xmn6G -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
  FML: MCP 9.42 Powered by Forge 14.23.5.2772 Optifine OptiFine_1.12.2_HD_U_E2 186 mods loaded, 186 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized

**Comment by BugmanBugman** [comment]
https://hastebin.com/gosocolide.makefile

**Comment by asiekierka** [comment]
Why is

>net.theexceptionist.coherentvillages.worldgen.villages.FrankStructurePieces$Field2.addComponentParts(FrankStructurePieces.java:577)

Coherent Villages setting beetroots to an age of 6, where it's clearly not allowed?
