### ISSUE TITLE
Crash with Blood Arsenal placing Block

### ISSUE THREAD

**Issue by dredhorse** [asiekierka/FoamFix#190]
Hi,

getting the following crash with BloodArsenal when trying to place a Blood Infused Plank (gotten from creative tab)

java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=half, clazz=class net.minecraft.block.BlockSlab$EnumBlockHalf, values=[top, bottom]} as it does not exist in BlockStateContainer{block=bloodarsenal:blood_infused_wooden_double_slab, properties=[variant]}
	at pl.asie.foamfix.common.FoamyBlockState.func_177226_a(FoamyBlockState.java:57)
	at net.minecraft.block.BlockSlab.func_180642_a(BlockSlab.java:98)
	at net.minecraft.block.Block.getStateForPlacement(Block.java:2254)
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:52)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:467)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

foamfix-0.10.3-1.12.2.jar
BloodArsenal-1.12.2-2.1.0-26.jar

**Comment by dredhorse** [comment]
https://github.com/Arcaratus/BloodArsenal/issues/143

**Comment by dredhorse** [comment]
BloodArsenal Issue as it seems
