### ISSUE TITLE
Crash on Startup - Anarchy Lawful Crash on Startup with Surge 5.0 - 1.10.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [asiekierka/FoamFix#20]
https://gist.github.com/P3rf3ctXZer0/57b2b77a271296694d7cf4c752816510

I did the tests you requested.

**Comment by asiekierka** [comment]
Remove OptiFine first.

**Comment by asiekierka** [comment]
Found it:

[12:43:54] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NullPointerException
[12:43:54] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraftforge.fml.common.FMLCommonHandler.getSide(FMLCommonHandler.java:191)
[12:43:54] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.epoxide.surge.features.FeatureManager.initFeatures(FeatureManager.java:26)
[12:43:54] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.epoxide.surge.features.FeatureManager.getFeature(FeatureManager.java:56)
[12:43:54] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.epoxide.surge.asm.SurgeTransformerManager.transform(SurgeTransformerManager.java:19)
[12:43:54] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:249)
[12:43:54] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	... 31 more

It's a bug in Surge.
