### ISSUE TITLE
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} to null on block minecraft:sticky_piston, it is not an allowed value

### ISSUE THREAD

**Issue by JCMais** [asiekierka/FoamFix#22]
Forge 1.10.2 - 12.18.3.2202
BOP 1.10.2-5.0.0.2109
FoamFix 0.5

Using Optifine, but doesn't looks like it's involved.

```
[Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} to null on block minecraft:sticky_piston, it is not an allowed value
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} to null on block minecraft:sticky_piston, it is not an allowed value
	at pl.asie.foamfix.common.FoamyBlockState.func_177226_a(FoamyBlockState.java:34) ~[foamfix-0.5.0-anarchy.jar:?]
	at net.minecraft.block.BlockPistonBase.func_176203_a(BlockPistonBase.java:424) ~[arj.class:?]
	at biomesoplenty.common.handler.AchievementEventHandler.onBlockPlaced(AchievementEventHandler.java:191) ~[AchievementEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_236_AchievementEventHandler_onBlockPlaced_PlaceEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerBlockPlace(ForgeEventFactory.java:151) ~[ForgeEventFactory.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:811) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:144) ~[adz.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:493) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
```

**Behaviour:**

https://gfycat.com/SevereRequiredIbadanmalimbe

Sorry for the low quality gif.

If you right click a sticky/normal piston after placing it, you place another one. If you break one, you get two.

Also if on server, other players cannot see the placed piston. They can only see after activating it for the first time.

**Comment by asiekierka** [comment]
Not OptiFine! This is *odd*...

**Comment by asiekierka** [comment]
Could you check if disabling experimental.smallPropertyStorage gets rid of the problem? (It should also be a good workaround, although it will increase RAM usage a bit)

**Comment by JCMais** [comment]
Tried it, still happens.

**Comment by asiekierka** [comment]
Could you also test (a) without FoamFix and (b) with Lawful?

**Comment by asiekierka** [comment]
https://github.com/asiekierka/FoamFix/issues/21

Confirmed thanks to @Ivorforce.

**Comment by JCMais** [comment]
Oopps. Still happens without foamfix. 😁 

It is a BOP issue: https://github.com/Glitchfiend/BiomesOPlenty/issues/926
