### ISSUE TITLE
java.lang.NoSuchMethodError: net.minecraftforge.fml.relauncher.ReflectionHelper.findField(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/reflect/Field;

### ISSUE THREAD

**Issue by ghost** [asiekierka/FoamFix#255]
No idea what's wrong here but here's a crash report that doesn't seem to have been reported before
```
[17:17:57] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  offlineskins (OfflineSkins-1.12.2-v6-core.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  MtqFixPlugin (mtqfix-1.12.2-1.1.0.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  LoadingPlugin (Quark-r1.5-145.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 3/24/20 5:17 PM
Description: Initializing game

java.lang.NoSuchMethodError: net.minecraftforge.fml.relauncher.ReflectionHelper.findField(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/reflect/Field;
	at net.minecraft.client.util.SearchTreeManager.func_110549_a(SourceFile:48)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.util.SearchTreeManager.func_110549_a(SourceFile:48)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1742198584 bytes (1661 MB) / 2460483584 bytes (2346 MB) up to 2460483584 bytes (2346 MB)
	JVM Flags: 3 total; -Xms2560m -Xmx2560m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E3 44 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version                  | Source                                           | Signature                                |
	|:----- |:------------------ |:------------------------ |:------------------------------------------------ |:---------------------------------------- |
	| UCH   | minecraft          | 1.12.2                   | minecraft.jar                                    | None                                     |
	| UCH   | mcp                | 9.42                     | minecraft.jar                                    | None                                     |
	| UCH   | FML                | 8.0.99.99                | modpack.jar                                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge              | 14.23.5.2768             | modpack.jar                                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | foamfixcore        | 7.7.4                    | minecraft.jar                                    | None                                     |
	| UCH   | actuallyadditions  | 1.12.2-r144              | ActuallyAdditions-1.12.2-r144.jar                | None                                     |
	| UCH   | jei                | 4.15.0.269               | jei_1.12.2-4.15.0.269.jar                        | None                                     |
	| UCH   | quark              | r1.5-145                 | Quark-r1.5-145.jar                               | None                                     |
	| UCH   | autoreglib         | 1.3-32                   | AutoRegLib-1.3-32.jar                            | None                                     |
	| UCH   | baubles            | 1.5.2                    | Baubles-1.12-1.5.2.jar                           | None                                     |
	| UCH   | biomesoplenty      | 7.0.1.2439               | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar    | None                                     |
	| UCH   | ctm                | MC1.12.2-0.3.3.22        | CTM-MC1.12.2-0.3.3.22.jar                        | None                                     |
	| UCH   | chisel             | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                     | None                                     |
	| UCH   | mantle             | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                         | None                                     |
	| UCH   | tconstruct         | 1.12.2-2.12.0.157        | TConstruct-1.12.2-2.12.0.157.jar                 | None                                     |
	| UCH   | ceramics           | 1.12-1.3.7               | Ceramics-1.12-1.3.7.jar                          | None                                     |
	| UCH   | codechickenlib     | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | redstoneflux       | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | cofhcore           | 4.6.3                    | CoFHCore-1.12.2-4.6.3.27-universal.jar           | None                                     |
	| UCH   | cofhworld          | 1.3.1                    | CoFHWorld-1.12.2-1.3.1.7-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | conarm             | 1.2.4                    | conarm-1.12.2-1.2.4.jar                          | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCH   | dynmap             | 3.0-beta-4-213           | Dynmap-3.0-beta-4-forge-1.12.2.jar               | None                                     |
	| UCH   | foamfix            | 0.10.10-1.12.2           | foamfix-0.10.10-1.12.2.jar                       | None                                     |
	| UCH   | furnaceoverhaul    | 2.2.0                    | FurnaceOverhaul-1.12.2-2.2.0.jar                 | None                                     |
	| UCH   | lex                | 1.0.8                    | LibEx-1.12.2-1.0.8.jar                           | None                                     |
	| UCH   | lootbags           | 2.5.8.5                  | LootBags-1.12.2-2.5.8.5.jar                      | None                                     |
	| UCH   | lycanitesmobs      | 2.0.6.3 - MC 1.12.2      | lycanitesmobs-1.12.2-2.0.6.3.jar                 | None                                     |
	| UCH   | thermalfoundation  | 2.6.3                    | ThermalFoundation-1.12.2-2.6.3.27-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | thermalexpansion   | 5.5.4                    | ThermalExpansion-1.12.2-5.5.4.43-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | netherfoundation   | 1.2.0                    | NetherFoundation-1.12.2-1.2.0-universal.jar      | None                                     |
	| UCH   | offlineskins       | 1.12.2-v6                | OfflineSkins-1.12.2-v6.jar                       | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCH   | oreberries         | 0.5.0                    | oreberries-1.12.x-0.5.0.jar                      | None                                     |
	| UCH   | oreexcavation      | 1.4.140                  | OreExcavation-1.4.140.jar                        | None                                     |
	| UCH   | taiga              | 1.12.2-1.3.3             | taiga-1.12.2-1.3.4.jar                           | None                                     |
	| UCH   | thermalcultivation | 0.3.3                    | ThermalCultivation-1.12.2-0.3.3.12-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | thermaldynamics    | 2.5.5                    | ThermalDynamics-1.12.2-2.5.5.21-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | thermalinnovation  | 0.3.3                    | ThermalInnovation-1.12.2-0.3.3.12-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | tcomplement        | 1.12.2-0.4.2             | TinkersComplement-1.12.2-0.4.2.jar               | None                                     |
	| UCH   | tinkertoolleveling | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar              | None                                     |
	| UCH   | vanilladeathchest  | 1.12.2-1.9.3.0           | vanilladeathchest-1.12.2-1.9.3.0.jar             | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
	| UCH   | xaerominimap       | 1.17.4                   | Xaeros_Minimap_1.17.4_Forge_1.12.jar             | None                                     |
	| UCH   | yoyos              | 1.12.2-1.3.3.25          | yoyos_1.12.2-1.3.3.25.jar                        | None                                     |
	| UCH   | matteroverdrive    | 0.7.0.0                  | MatterOverdrive-1.12.2-0.7.1.0-universal.jar     | None                                     |
	| UD    | mtqfix             | 1.1.0                    | minecraft.jar                                    | None                                     |

	Loaded coremods (and transformers): 
offlineskins (OfflineSkins-1.12.2-v6-core.jar)
  lain.mods.skins.init.forge.asm.ASMTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
MtqFixPlugin (mtqfix-1.12.2-1.1.0.jar)
  jmn.mods.mtqfix.AsmTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (Quark-r1.5-145.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleMelter (Enabled/Not Forced)
		- ModuleArmor (Enabled/Not Forced)
		- ModuleSteelworks (Enabled/Not Forced)
		- CeramicsPlugin (Enabled/Not Forced)
		- ChiselPlugin (Enabled/Not Forced)
		- ToolLevelingPlugin (Enabled/Not Forced)
		- Oredict (Enabled/Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4276, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Pentium(R) CPU N3530 @ 2.16GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.4276
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 4
```

**Comment by asiekierka** [comment]
Have you tried upgrading Forge?

**Comment by ghost** [comment]
Oh ok, it's working with latest Forge for 1.12.2; I was using the recommended version.

Maybe this should be added to the common crashes info.

now what's with the spiteful description lol ![](https://m9vx.qonq.gq)
