### ISSUE TITLE
FoamFix crashes if packageManifests field is not in LaunchClassLoader

### ISSUE THREAD

**Issue by nallar** [asiekierka/FoamFix#26]
When `B:dummyPackageManifestMap=false`, foamfix still tries to get the `packageManifests` field, as this line isn't in the if.

```java
		Field packageManifestsField = ReflectionHelper.findField(LaunchClassLoader.class, "packageManifests");
// snip
		if (FoamFixShared.config.lwDummyPackageManifestMap) {
```

`packageManifests` [will be removed in a future version of launchwrapper](https://github.com/Mojang/LegacyLauncher/commit/a4801b70f8a0148c6e6279ec2e91527e8019e1c8), so ideally this should not crash even if the config option is turned on.

```
Caused by: java.lang.NoSuchFieldException: packageManifests
        at java.lang.Class.getDeclaredField(Unknown Source) ~[?:1.8.0_121]
        at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:87) ~[FTBserver-1.10.2-12.18.3.2202-universal.jar:?]
        at pl.asie.foamfix.ProxyCommon.optimizeLaunchWrapper(ProxyCommon.java:51) ~[foamfix-0.5.0-BETA2-anarchy.jar:?]
        at pl.asie.foamfix.ProxyCommon.postInit(ProxyCommon.java:119) ~[foamfix-0.5.0-BETA2-anarchy.jar:?]
        at pl.asie.foamfix.FoamFix.postInit(FoamFix.java:73) ~[foamfix-0.5.0-BETA2-anarchy.jar:?]
```

**Comment by asiekierka** [comment]
Good to know!

Generally, the removal of packageManifests is directly related to the existence of this tweak - but I should take care of handling the lack of packageManifests in the first place.
