### ISSUE TITLE
Ears Profile lookup failed

### ISSUE THREAD

**Issue by couleurm** [asiekierka/FoamFix#298]
this is spamming the fuck out of my logs, any clues?
```
[23:27:26] [Ears lookup thread (00062f34-a2bc-4cff-b403-d6b8700d50c4)/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.NullPointerException
[23:27:26] [Ears lookup thread (00062f34-a2bc-4cff-b403-d6b8700d50c4)/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at pl.asie.foamfix.repack.com.unascribed.ears.legacy.mcauthlib.util.HTTP.processResponse(HTTP.java:239)
[23:27:26] [Ears lookup thread (00062f34-a2bc-4cff-b403-d6b8700d50c4)/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at pl.asie.foamfix.repack.com.unascribed.ears.legacy.mcauthlib.util.HTTP.performGetRequest(HTTP.java:199)
[23:27:26] [Ears lookup thread (00062f34-a2bc-4cff-b403-d6b8700d50c4)/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at pl.asie.foamfix.repack.com.unascribed.ears.legacy.mcauthlib.util.HTTP.makeRequest(HTTP.java:91)
[23:27:26] [Ears lookup thread (00062f34-a2bc-4cff-b403-d6b8700d50c4)/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at pl.asie.foamfix.repack.com.unascribed.ears.legacy.mcauthlib.util.HTTP.makeRequest(HTTP.java:108)
[23:27:26] [Ears lookup thread (00062f34-a2bc-4cff-b403-d6b8700d50c4)/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at pl.asie.foamfix.repack.com.unascribed.ears.legacy.mcauthlib.service.SessionService.fillProfileProperties(SessionService.java:69)
[23:27:26] [Ears lookup thread (00062f34-a2bc-4cff-b403-d6b8700d50c4)/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at pl.asie.foamfix.repack.com.unascribed.ears.legacy.LegacyHelper.getSkinUrl(LegacyHelper.java:140)
[23:27:26] [Ears lookup thread (00062f34-a2bc-4cff-b403-d6b8700d50c4)/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at pl.asie.foamfix.repack.com.unascribed.ears.legacy.LegacyHelper$2.run(LegacyHelper.java:93)
[23:27:26] [Ears lookup thread (00062f34-a2bc-4cff-b403-d6b8700d50c4)/INFO] [STDERR]: [pl.asie.foamfix.repack.com.unascribed.ears.legacy.LegacyHelper:getSkinUrl:152]: [Ears] Profile lookup failed
```

**Comment by DarianLStephens** [comment]
I've been getting that, too.
Even tried installing Ears, but it didn't help anything.
Going back to an old version of FoamFix got rid of it, though.
