### ISSUE TITLE
Can't make a single player world

### ISSUE THREAD

**Issue by Szymnx** [asiekierka/FoamFix#299]
I downloaded Skyexchange and when i started minecraft everything went well until i started making a single player world to actually play, then it just froze on generating terrain. 
Here's the crash file
[crash-2023-05-12_21.57.36-server.txt](https://github.com/asiekierka/FoamFix/files/11467435/crash-2023-05-12_21.57.36-server.txt)

**Comment by asiekierka** [comment]
```
Caused by: java.lang.NumberFormatException: For input string: "01_13"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.feed_the_beast.ftbu.world.backups.Backups.init(Backups.java:76)
        at com.feed_the_beast.ftbu.FTBU.serverStarted(FTBU.java:72)
```
That's not a FoamFix issue, that's an FTBU issue.
