### ISSUE TITLE
Survivalist isn't compatible with Foamfix

### ISSUE THREAD

**Issue by SirCrimsonDeath** [asiekierka/FoamFix#31]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.5.3-anarchy.jar)
  LoadingPlugin (Quark-r1.2-77.jar)
  offlineskins (OfflineSkins-1.11.2-v1.jar)
  TANLoadingPlugin (ToughAsNails-1.11-2.0.4.jar)
  LoadingPlugin (HardcoreDarkness-MC1.11-1.8.1.jar)
  IvToolkit (IvToolkit-1.3.1.jar)
  BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.3.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 1/29/17 5:04 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Survivalist (survivalist)
Caused by: java.lang.NoClassDefFoundError: gigaherz/survivalist/shadow/common/BlockRegistered
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:546)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:563)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:229)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Caused by: java.lang.ClassNotFoundException: gigaherz.survivalist.shadow.common.BlockRegistered
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 42 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer pl.asie.foamfix.coremod.FoamFixTransformer@30cf17 from coremod Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again.
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:257)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 44 more
Caused by: java.lang.NullPointerException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at pl.asie.foamfix.coremod.BlockPosPatch.patchOtherClass(BlockPosPatch.java:135)
	at pl.asie.foamfix.coremod.FoamFixTransformer.transform(FoamFixTransformer.java:105)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:253)
	... 46 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 521222648 bytes (497 MB) / 722468864 bytes (689 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 7 total; -XX:+UseG1GC -XX:+DisableExplicitGC -XX:MaxGCPauseMillis=10 -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2226 Optifine OptiFine_1.11.2_HD_U_B7_pre 30 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2226-universal.jar) 
	UC	forge{13.20.0.2226} [Minecraft Forge] (forge-1.11.2-13.20.0.2226-universal.jar) 
	UC	ivtoolkit{1.3.1} [IvToolkit] (minecraft.jar) 
	UC	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UC	ambience{GRADLE:VERSION-GRADLE:BUILD} [Ambience] (Ambience 1.1-8.jar) 
	UC	jei{4.2.4.226} [Just Enough Items] (jei_1.11.2-4.2.4.226.jar) 
	UC	appleskin{1.0.6} [AppleSkin] (AppleSkin-mc1.11-1.0.6.jar) 
	UC	quark{r1.2-77} [Quark] (Quark-r1.2-77.jar) 
	UC	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UC	babyanimals{1.11} [Baby Animals Model Swapper] (BabyAnimals-1.11.jar) 
	UC	betterfoliage{2.1.3} [Better Foliage] (BetterFoliage-MC1.11.2-2.1.3.jar) 
	UC	biomesoplenty{6.0.1.2145} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.0.1.2145-universal.jar) 
	UC	claybucket{1.1} [Clay Bucket] (ClayBucket-1.11-1.0.jar) 
	UC	embers{0.107} [Embers] (embers-0.107.jar) 
	UC	fastleavedecay{1.2.3} [Fast Leave Decay] (FastLeaveDecay-MC1.11-1.2.3.jar) 
	UC	foamfix{@VERSION@} [FoamFix] (foamfix-0.5.3-anarchy.jar) 
	UC	friendlyfire{1.4.0} [Friendly Fire] (FriendlyFire-1.11-1.4.0.jar) 
	UC	grapplemod{1.11-v9} [Grappling hook mod] (grapplemod-1.11-v9.jar) 
	UC	hardcoredarkness{1.8.1} [Hardcore Darkness] (HardcoreDarkness-MC1.11-1.8.1.jar) 
	UC	levels{r1.0.0} [Levels] (Levels 2-1.11.2-r1.0.0.jar) 
	UC	levelup{${version}} [Level Up!] (LevelUp!-0.13.1-1.11.jar) 
	UC	offlineskins{1.11.2-v1} [OfflineSkins] (OfflineSkins-1.11.2-v1.jar) 
	UC	reccomplex{1.2.7} [Recurrent Complex] (RecurrentComplex-1.2.7.jar) 
	UC	simulatednights{1.11.2-1.1.2} [Simulated Nights] (simulatednights-1.11.2-1.1.2.jar) 
	UC	sophisticatedwolves{3.6.4} [Sophisticated Wolves] (SophisticatedWolves-3.6.4.jar) 
	UC	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.11.jar) 
	UE	survivalist{1.8.0} [Survivalist] (Survivalist-1.11.0-1.8.0.jar) 
	UC	toughasnails{@MOD_VERSION@} [Tough As Nails] (ToughAsNails-1.11-2.0.4.jar) 
	Loaded coremods (and transformers): 
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.5.3-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LoadingPlugin (Quark-r1.2-77.jar)
  vazkii.quark.base.asm.ClassTransformer
offlineskins (OfflineSkins-1.11.2-v1.jar)
  lain.mods.skins.asm.ASMTransformer
TANLoadingPlugin (ToughAsNails-1.11-2.0.4.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
LoadingPlugin (HardcoreDarkness-MC1.11-1.8.1.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.1.jar)
  
BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.3.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1.2' Renderer: 'GeForce 7025 / nForce 630a/integrated/SSE2/3DNOW!'
	OptiFine Version: OptiFine_1.11.2_HD_U_B7_pre
	Render Distance Chunks: 5
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1.2
	OpenGlRenderer: GeForce 7025 / nForce 630a/integrated/SSE2/3DNOW!
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2

**Comment by SirCrimsonDeath** [comment]
Wasn't Foamfix fault.
