### ISSUE TITLE
[1.11.2] Crash at pl.asie.foamfix.common.FoamyBlockState.func_177226_a(FoamyBlockState.java:34)

### ISSUE THREAD

**Issue by PrinceOfAmber** [asiekierka/FoamFix#38]
When this happened i was walking around at night, and was about to shoot an arrow at a witch

Installed was foamfix-0.6.2-beta2-anarchy.jar

Full log

http://pastebin.com/TDTPe0Fw

In that log file around line 1482 it says

java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block plants:cataplant, it is not an allowed value
    at pl.asie.foamfix.common.FoamyBlockState.func_177226_a(FoamyBlockState.java:34) ~[foamfix-0.6.2-beta2-anarchy.jar:?]
    at shadows.plants.util.Util.getStateByChance(Util.java:321) ~[Util.class:?]
    at shadows.plants.util.Decorator.onWorldDecoration(Decorator.java:35) ~[Decorator.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_524_Decorator_onWorldDecoration_Decorate.invoke(.dynamic) ~[?:?]

So it might be a mod conflict with this plants mod 
https://mods.curse.com/mc-mods/minecraft/257229-plants

Ill cross post the issue to that mods issue tracker as well  , no idea which mod needs the fix https://github.com/Shadows-of-Fire/Plants/issues/17

**Comment by PrinceOfAmber** [comment]
Nevermind , was the other mod :)
