### ISSUE TITLE
[1.10.2] Log gets spammed with things regarding foamfix?

### ISSUE THREAD

**Issue by KristjanKr** [asiekierka/FoamFix#50]
Log gets spammed with stuff regarding foamfix: https://paste.ee/p/v9jUg
such as: 
[14:09:20] [Thread-26/INFO] [STDERR]: [pl.asie.classcachetweaker.ClassCache:save:337]: java.util.ConcurrentModificationException
[14:09:20] [Thread-26/INFO] [STDERR]: [pl.asie.classcachetweaker.ClassCache:save:337]: 	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
[14:09:20] [Thread-26/INFO] [STDERR]: [pl.asie.classcachetweaker.ClassCache:save:337]: 	at java.util.HashMap$ValueIterator.next(Unknown Source)
[14:09:20] [Thread-26/INFO] [STDERR]: [pl.asie.classcachetweaker.ClassCache:save:337]: 	at pl.asie.classcachetweaker.ClassCache.save(ClassCache.java:280)
[14:09:20] [Thread-26/INFO] [STDERR]: [pl.asie.classcachetweaker.ClassCache:save:337]: 	at pl.asie.classcachetweaker.ClassCache.access$100(ClassCache.java:31)
[14:09:20] [Thread-26/INFO] [STDERR]: [pl.asie.classcachetweaker.ClassCache:save:337]: 	at pl.asie.classcachetweaker.ClassCache$1.run(ClassCache.java:217)
[14:09:20] [Thread-26/INFO] [STDERR]: [pl.asie.classcachetweaker.ClassCache:save:337]: 	at java.lang.Thread.run(Unknown Source)

**Comment by asiekierka** [comment]
That's ClassCacheTweaker (which is not really supported), not FoamFix.
