### ISSUE TITLE
Error - Mixin apply failed on Sponge/Forge server

### ISSUE THREAD

**Issue by Heartfyre** [asiekierka/FoamFix#53]
Hey there,

I ran into a problem with your latest FoamFix 0.6.2 "Anarchy"-version on a Sponge/ Forge server setup.

Let me point out an issue on their Github I created: [Sponge](https://github.com/SpongePowered/SpongeForge/issues/1485)

Just a quick summary - I was getting an error with the "Anarchy"-version together with Sponge version: 1.10.2-2281-5.2.0-BETA-2300 and with Forge: 2281.

To be clear, this error doesn't appear with the "Lawful"-version.

Please let me know, if you need any further info!

Here's the exact error message:

```[20:44:07] [main/INFO] [STDOUT]: [pl.asie.foamfix.coremod.FoamFixReplaceClassSimpleName$FFMethodVisitor:visitMethodInsn:47]: Replaced INVOKEVIRTUAL getSimpleName
[20:44:08] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[20:44:08] [main/INFO]: [STDOUT]: Spliced in METHOD: net.minecraft.block.state.BlockStateContainer.createState
[20:44:09] [main/INFO]: [STDOUT]: Spliced in METHOD: net.minecraft.block.state.BlockStateContainer.createState
[20:44:09] [main/INFO] [mixin]: Instancing error handler class org.spongepowered.mod.mixin.handler.MixinErrorHandler
[20:44:09] [main/WARN] [mixin]: Mixin apply failed mixins.common.core.optional.json:util.math.MixinMutableBlockPos -> net.minecraft.util.math.BlockPos$MutableBlockPos: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Shadow field field_177997_b was not located in the target class
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Shadow field field_177997_b was not located in the target class
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:448) ~[spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:204) ~[spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:186) ~[spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1103) ~[spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:245) ~[spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:281) ~[spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:816) [spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:786) [spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:591) [spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:183) [spongeforge-1.11.2-2282-7.0.0-BETA-2301.jar:1.11.2-2282-7.0.0-BETA-2301]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_131]
        at org.spongepowered.common.registry.provider.BlockPropertyIdProvider.<init>(BlockPropertyIdProvider.java:146) [BlockPropertyIdProvider.class:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.common.registry.provider.BlockPropertyIdProvider$Holder.<clinit>(BlockPropertyIdProvider.java:281) [BlockPropertyIdProvider$Holder.class:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.common.registry.provider.BlockPropertyIdProvider.getInstance(BlockPropertyIdProvider.java:49) [BlockPropertyIdProvider.class:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.common.registry.provider.BlockPropertyIdProvider.getIdAndTryRegistration(BlockPropertyIdProvider.java:67) [BlockPropertyIdProvider.class:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.common.registry.type.BlockTypeRegistryModule.registerBlockTrait(BlockTypeRegistryModule.java:128) [BlockTypeRegistryModule.class:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.common.registry.type.BlockTypeRegistryModule.registerFromGameData(BlockTypeRegistryModule.java:116) [BlockTypeRegistryModule.class:1.11.2-2282-7.0.0-BETA-2301]
        at net.minecraft.block.Block.handler$onRegisterBlock$zzl000(Block.java:2660) [alu.class:?]
        at net.minecraft.block.Block.func_176215_a(Block.java:2448) [alu.class:?]
        at net.minecraft.block.Block.func_176219_a(Block.java:2452) [alu.class:?]
        at net.minecraft.block.Block.func_149671_p(Block.java:2150) [alu.class:?]
        at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:491) [kt.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1419) [MinecraftServer.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62) [yucom.jar:?]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31) [yucom.jar:?]
[20:44:15] [Server thread/INFO]: Starting minecraft server version 1.11.2

**Comment by johnneijzen** [comment]
I wonder if you set B:optimizedBlockPos=true to B:optimizedBlockPos=false in config file if will work because that is only reference field_177997_b that is located in coremod/BlockPosPatch.java

**Comment by johnneijzen** [comment]
it was also mentions on SpongeCommon issue area

https://github.com/SpongePowered/SpongeCommon/issues/1272

**Comment by asiekierka** [comment]
Good point. I'll document it on the site.
