### ISSUE TITLE
[1.10.2] Crash with LoamFix Anarchy on start up

### ISSUE THREAD

**Issue by Draskh** [asiekierka/FoamFix#71]
The game crashes if foam fix is present.

Description: Initializing game

java.lang.NoSuchFieldError: firstLoad
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:61)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by asiekierka** [comment]
Please update Forge.

**Comment by Draskh** [comment]
Why does LoamFix not use the recommended version?

**Comment by asiekierka** [comment]
Because the latest version usually has many more bugfixes and additional features which some mods rely on, and modpacks seem to generally also use the latest version?

**Comment by Draskh** [comment]
Alright! I will update!
