### ISSUE TITLE
I'm getting an unclear crash and I think it's foamfix

### ISSUE THREAD

**Issue by nargyriou** [asiekierka/FoamFix#73]
EDIT: "Known Issues    "java.lang.NoSuchFieldError: firstLoad" <- on Minecraft 1.10/1.11, that means you should update Forge"

No idea why this didn't show up first on google. Sorry !

Hey

I'm getting this crash on Farming Valley 0.8.0 (https://minecraft.curseforge.com/projects/farming-valley)

https://pastebin.com/YBJstk6b

```
java.lang.NoSuchFieldError: firstLoad
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:61)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
```

So I did a quick google search and the fix suggestion was to disable optifine. I don't have fastcraft or anything so I tried to disable foamfix. And somehow, it worked.

When I enable foamfix back, I get the exact same crash.

So foamfix could be the problem here. I'm using "foamfix-0.6.2-anarchy.jar" with the default config from Farming Valley (https://pastebin.com/iNjLzhVv)

**Comment by asiekierka** [comment]
Update Forge. Also, update FoamFix.

**Comment by nargyriou** [comment]
yep I found out and edited before you replied. It's weird that google didn't point this out.

**Comment by asiekierka** [comment]
The official FoamFix website points this out as of yesterday.

**Comment by nargyriou** [comment]
Oh it's from yesterday, I see. Probably why google didn't direct me to it. 

That's where I found the fix (purely by accident while trying to update foamfix)

**Comment by asiekierka** [comment]
Okay! I'm glad I could help you.
