### ISSUE TITLE
Log spam during game loading since MinecraftForge 1.12.2-14.23.0.2523

### ISSUE THREAD

**Issue by 3TUSK** [asiekierka/FoamFix#91]
`net.minecraftforge.client.model.ItemLayerModel$BakedItemModel` is now a public class, `net.minecraftforge.client.model.BakedItemModel`, since https://github.com/MinecraftForge/MinecraftForge/commit/b5e88dd07b4aa7a719c5c44a89aa735b6ca891ce became part of MinecraftForge (first appears in 14.23.0.2523).  
This issue does not block game from loading normally.

````
[21:04:01] [main/INFO] [STDERR]: [pl.asie.foamfix.util.MethodHandleHelper:findFieldSetter:44]: java.lang.ClassNotFoundException: net.minecraftforge.client.model.ItemLayerModel$BakedItemModel
[21:04:01] [main/INFO] [STDERR]: [pl.asie.foamfix.util.MethodHandleHelper:findFieldSetter:44]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[21:04:01] [main/INFO] [STDERR]: [pl.asie.foamfix.util.MethodHandleHelper:findFieldSetter:44]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[21:04:01] [main/INFO] [STDERR]: [pl.asie.foamfix.util.MethodHandleHelper:findFieldSetter:44]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[21:04:01] [main/INFO] [STDERR]: [pl.asie.foamfix.util.MethodHandleHelper:findFieldSetter:44]: 	at java.lang.Class.forName0(Native Method)
[21:04:01] [main/INFO] [STDERR]: [pl.asie.foamfix.util.MethodHandleHelper:findFieldSetter:44]: 	at java.lang.Class.forName(Class.java:264)
[21:04:01] [main/INFO] [STDERR]: [pl.asie.foamfix.util.MethodHandleHelper:findFieldSetter:44]: 	at pl.asie.foamfix.util.MethodHandleHelper.findFieldSetter(MethodHandleHelper.java:42)
[21:04:01] [main/INFO] [STDERR]: [pl.asie.foamfix.util.MethodHandleHelper:findFieldSetter:44]: 	at pl.asie.foamfix.client.Deduplicator.<clinit>(Deduplicator.java:86)
[21:04:01] [main/INFO] [STDERR]: [pl.asie.foamfix.util.MethodHandleHelper:findFieldSetter:44]: 	at pl.asie.foamfix.ProxyClient.<clinit>(ProxyClient.java:49)
[21:04:01] [main/INFO] [STDERR]: [pl.asie.foamfix.util.MethodHandleHelper:findFieldSetter:44]: 	at java.lang.Class.forName0(Native Method)
[21:04:01] [main/INFO] [STDERR]: [pl.asie.foamfix.util.MethodHandleHelper:findFieldSetter:44]: 	at java.lang.Class.forName(Class.java:348)
[21:04:01] [main/INFO] [STDERR]: [pl.asie.foamfix.util.MethodHandleHelper:findFieldSetter:44]: 	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:85)
[21:04:01] [main/INFO] [STDERR]: [pl.asie.foamfix.util.MethodHandleHelper:findFieldSetter:44]: 	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:583)
````
(Truncating rest part)

> Still curious how come nobody reports here. *Someone* should have already reported it... or there has been a temporary fix or workaround?

**Comment by asiekierka** [comment]
Fixed in 0.8.x-1.12.2
